name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "nightly"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Tagged release
        if: ${{ github.ref_name != 'nightly' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ github.token }}
          prerelease: false

      - name: Nightly release
        if: ${{ github.ref_name == 'nightly' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PAT }}
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Release"
